Initial authentication backend
endlessm/kolibri-desktop-auth-plugin pull request #1
Opened 2021-10-11 15:26 UTC by danigm

https://phabricator.endlessm.com/T32614

2021-10-12 22:09 UTC, dylanmccall requested changes
This looks like a good start. Thanks for getting things moving, @danigm! I agree with using a login URL rather than a middleware thing. That should be nice and easy to work with.

So, just one small request about naming the thing :)

2021-10-14 09:48 UTC, danigm commented on Pipfile
> +python_version = "3.7"
I've added the lock file

2021-10-14 14:03 UTC, manuq commented on kolibri_desktop_auth_plugin/kolibri_plugin.py
> +        return r"daemon-auth/"
The `deamon-auth/` URL prefix doesn't say much to me. I'd prefer if it includes something about "desktop user" or "system user". What about?: 
```suggestion
        return r"desktop-user-auth/"
```

Or maybe even better, leave it to the default which is a lower-case version of the plugin name. And rename the class name to DesktopAuth or DesktopUserAuth (I'm tempted to request a repo rename again to `kolibri-desktop-user-auth-plugin`).

2021-10-14 14:55 UTC, manuq commented on kolibri_desktop_auth_plugin/migrations/0001_initial.py
> +            name="DaemonAuthUser",
This should be renamed also along with the other renames for consistency. Maybe "DesktopUser"?

2021-10-18 17:06 UTC, merged